### ISSUE TITLE
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by HummingMind** [antfu-collective/vite-ssg#412]
### Describe the bug

When building the project with vite-ssg build I get the following warning:
`(node:8720) [DEP0040] DeprecationWarning: The 'punycode' module is deprecated. Please use a userland alternative instead.`

![image](https://github.com/user-attachments/assets/8544dd1e-4d07-4745-a6a3-8e31d9a9d4a4)

### Reproduction

Any project using 0.23.8 version

### System Info

```Shell
Node 22.5.1
NPM 10.8.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by HummingMind** [comment]
Looks like tough-cookie used by jsdom is the culprit. The 5.0.0-rc versions of touch-cookie drop the deprecated psl package that causes this warning. So, for NPM, I ended up using:

`
  "overrides": {
    "jsdom": {
      "tough-cookie": "5.0.0-rc.4"
    }
  }
`

**Comment by HummingMind** [comment]
I am not sure why I closed this. 🤣 Even though the override works, this should really be fixed in vite-ssg.

Can jsdom be upgraded to version ^25 in vite-ssg dependencies?

**Comment by antfu** [comment]
Upgraded, thanks
