### ISSUE TITLE
An empty .vite-ssg-temp folder is left after every build

### ISSUE THREAD

**Issue by HummingMind** [antfu-collective/vite-ssg#413]
### Describe the bug

An empty .vite-ssg-temp folder is left after every build in VSCode:

![image](https://github.com/user-attachments/assets/3eb0751e-8f94-4b76-892a-9bbc54a0890a)

I imagine this folder should be removed after each build is completed, since it is a temporary folder.

### Reproduction

Every project using version 0.24.0

### System Info

```Shell
Any system
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by akirarika** [comment]
+1

**Comment by HummingMind** [comment]
Not sure how to do a pull request, but the issue seems to be here, in the build.ts file:

![image](https://github.com/user-attachments/assets/5bf1ec29-b003-4bd0-a9c6-eeb8894b63fa)

ssgOut gets set to a random folder within the .vite-ssg-temp parent folder.

Then, at the start of the build, these lines don't actually do anything:

![image](https://github.com/user-attachments/assets/1e76381e-1102-4fc6-912d-8ea7d0feedd8)

As the random folder name would be different from the last run.

And then finally:

![image](https://github.com/user-attachments/assets/121c2eaf-9783-4190-91c8-840891a0a877)

Removes the random folder, but not the parent folder.

So, one possible fix would be to:
` const ssgOutTempFolder = join(root, '.vite-ssg-temp')`

And in places where you check whether ssgOut folder exists, doing this instead:
`await fs.remove(ssgOutTempFolder)`
